### ISSUE TITLE
current zImage_dtb appears to omit wifi module support

### ISSUE THREAD

**Issue by alexanderupton** [NolanNicholson/GunCon2-MiSTer#1]
current zImage_dtb appears to omit wifi module support. After switching back to the stock latest public release wifi functionality returns.

After switching back here's the output of a few commands that may help identify if the test Kernel has driver parity with the standard public release::

lsmod:
<pre>Module                  Size  Used by
88x2bu               2707456  0
cfg80211              606208  1 88x2bu</pre>

#wifi adapter
lsusb:  
<pre>Bus 001 Device 005: ID 7392:b822 Edimax Technology Co., Ltd AC1200 MU-MIMO USB2.0 Adapter</pre>

Happy to capture any other output that may be helpful towards resolution

**Comment by NolanNicholson** [comment]
Thanks for the diagnostic info! It'll come in very handy if I need to make any other patched kernels for features down the road.

In the meantime, the GunCon 2 and 3 drivers are now part of the official Linux-Kernel_MiSTer repo, so the zImage_dtb here is no longer needed. I'll be removing it and updating the documentation shortly.
