### ISSUE TITLE
@NolanNicholson - Sinden Lightgun and MiSTer support.

### ISSUE THREAD

**Issue by wiggy808** [NolanNicholson/GunCon2-MiSTer#2]
Hey Nolan, 

Wasn't sure how else to get ahold of you. 
I'm an admin on the Sinden team and was hoping I could discuss with you a path for getting the Sinden Lightguns to work on the MiSTer directly (without any external hardware). 

You can contact me via replying here (I think I'll get notified) or on discord as "wiggy808 #3221" 

Thanks!

**Comment by NolanNicholson** [comment]
I've reached out over Discord. Cheers!
